<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ajouter au panier</name>
   <tag></tag>
   <elementGuidId>4d8f2373-e7f6-4ef6-b3c2-c85f09e07589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[5]//footer[1]//form[1]//button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad31467b-4287-4e4a-bb8e-ac091996e10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08a32ace-c654-4838-978e-e5020147cc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add btn _prim -pea _md</value>
      <webElementGuid>44c37f34-a5ea-495f-b028-3dab8c62e318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>89cd5642-9148-47d3-91a0-f576eb87ba1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>in</value>
      <webElementGuid>3a3ee558-b2cf-403e-901a-ef04bec3815f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajouter au panier</value>
      <webElementGuid>08ce5a99-ee71-42bd-9cb0-77ed25769a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jm&quot;)/main[@class=&quot;has-b2top -pts&quot;]/div[@class=&quot;aim row -pbm&quot;]/div[@class=&quot;-pvs col12&quot;]/section[@class=&quot;card -fh&quot;]/div[@class=&quot;-paxs row _no-g _4cl-3cm-shs&quot;]/article[@class=&quot;prd _fb col c-prd&quot;]/footer[@class=&quot;ft&quot;]/form[@class=&quot;-df -i-ctr -pr -j-bet&quot;]/button[@class=&quot;add btn _prim -pea _md&quot;]</value>
      <webElementGuid>021afebb-8f49-47d2-a3f4-88f679947616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='action'])[2]</value>
      <webElementGuid>247e5bf0-c56e-443d-a370-a8e4863a9b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jm']/main/div[2]/div[3]/section/div/article[4]/footer/form/button</value>
      <webElementGuid>997d93dc-57fc-4a28-a53d-ba25dead89f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Msi Micro Casque Headset Gamer - Immerse GH20 - Noir'])[1]/following::button[1]</value>
      <webElementGuid>5183c9bc-f66a-442b-bcf7-59c77677ca10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter au panier'])[3]/following::button[1]</value>
      <webElementGuid>a198b991-5c7c-46d0-8cd9-c7237281d988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Msi Combo Clavier Souris Gamer - VIGOR GK30 Combo White - Blanc RGB'])[1]/preceding::button[1]</value>
      <webElementGuid>d3214dd8-9cc0-4b60-9d19-de07c36e87af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajouter au panier'])[5]/preceding::button[1]</value>
      <webElementGuid>8cba353a-5b29-4656-95fd-89a8b82732fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[4]/footer/form/button</value>
      <webElementGuid>68269acc-dc22-4ec3-9e05-af19281917a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'action' and (text() = 'Ajouter au panier' or . = 'Ajouter au panier')]</value>
      <webElementGuid>9849a23e-2395-4cf3-80fe-972adc904c9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
