<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendez sur Jumia_q</name>
   <tag></tag>
   <elementGuidId>d2ebe42e-988b-4948-9a09-04be6b1ae064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fi-q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fi-q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b44005e5-b893-4067-a762-15d4e2244bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b85d2a1a-8efc-4bb6-8294-41484e243bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>bdfea472-d333-4bc2-b1e9-deae16681890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fi-q</value>
      <webElementGuid>ddd3282d-185d-48cd-acea-502279b2519f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cherchez un produit, une marque ou une catégorie</value>
      <webElementGuid>2ec9b1c1-c5be-4f08-9fce-92b86f4d1edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>e1baac5d-f041-4bad-8a05-9ef0b90bd3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d400cb4b-88d2-47a1-a693-ab1da7ce977d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fi-q&quot;)</value>
      <webElementGuid>f8099b90-d6c1-449d-a601-d1115d052108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fi-q']</value>
      <webElementGuid>b4e76a07-4f8a-499f-8f6a-a922f4355a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search']/div/input</value>
      <webElementGuid>fcd9f04d-db73-4dad-88b4-a9fe370d3628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3d37c24b-9373-4ccc-8321-b63a77a6b62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'q' and @id = 'fi-q' and @placeholder = 'Cherchez un produit, une marque ou une catégorie']</value>
      <webElementGuid>cc6082d4-e50b-4bbd-a85d-24d1c254bc7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
